const allRoles=['admin','seller','producer','buyer','storeman','manager'];
const allRolesObj={
					admin:'管理员',
					seller:'销售员',
					producer:'生产员',
					buyer:'采购员',
					storeman:'仓库管理员',
					manager:'主管'
				};
const menuRouter=[
	//主页
	{
		name:'Start',
		path:'/',
		component:()=>import('@/views/Home.vue'),
		meta:{
				title:'开始页',
				icon:'',
				roles:allRoles,
				root:'',
				index:0
			},
	},
	{
		name:'Home',
		path:'/home',
		component:()=>import('@/views/Home.vue'),
		meta:{
				title:'首页',
				icon:'',
				roles:allRoles,
				root:'',
				index:0
			},
	},
	//客户信息
	{
		name:'Customer',
		path:'/customer',
		component:()=>import('@/views/Client.vue'),
		meta:{
				title:'客户信息',
				icon:'',
				roles:['admin','seller','manager'],
				root:'InfoRoot',
				index:2
			},
	},
	//供应商
	{
		name:'Supplier',
		path:'/supplier',
		component:()=>import('@/views/Client.vue'),
		meta:{
				title:'供应商信息',
				icon:'',
				roles:['admin','buyer','manager'],
				root:'InfoRoot',
				index:1
			},
	},
	//人员信息
	{
		name:'Staff',
		path:'/staff',
		component:()=>import('@/views/User.vue'),
		meta:{
				title:'员工信息',
				icon:'',
				roles:allRoles,
				root:'InfoRoot',
				index:0
			},
	},
	//货物信息
	{
		name:'Goods',
		path:'/goods',
		component:()=>import('@/views/Goods.vue'),
		meta:{
				title:'货物信息',
				icon:'',
				roles:['admin','buyer','producer','manager'],
				root:'InfoRoot',
				index:3
			},
	},
	//采购需求
	{
		name:'MatterNeed',
		path:'/matterNeed',
		component:()=>import('@/views/NeedPlan.vue'),
		meta:{
				title:'采购需求',
				icon:'',
				roles:['admin','buyer','producer'],
				root:'NeedRoot',
				index:0
			},
	},
	//生产需求
	{
		name:'ProductNeed',
		path:'/productNeed',
		component:()=>import('@/views/NeedPlan.vue'),
		meta:{
				title:'生产需求',
				icon:'',
				roles:['admin','producer','seller'],
				root:'NeedRoot',
				index:0
			},
	},
	//计划信息
	{
		name:'Plan',
		path:'/plan',
		component:()=>import('@/views/NeedPlan.vue'),
		meta:{
				title:'计划信息',
				icon:'',
				roles:['admin','buyer','manager','seller','producer'],
				root:'PlanRoot',
				index:0
			},
	},
	//需求详情
	{
		name:'NeedDetail',
		path:'/needDetail',
		component:()=>import('@/views/NPDetail.vue'),
		meta:{
				title:'需求详情',
				icon:'',
				roles:['admin','buyer','manager','seller','producer'],
				root:'',
				index:0
			},
	},
  //计划详情
  {
  	name:'PlanDetail',
  	path:'/planDetail',
  	component:()=>import('@/views/NPDetail.vue'),
  	meta:{
  			title:'计划详情',
  			icon:'',
  			roles:['admin','buyer','manager','seller','producer'],
  			root:'',
  			index:0
  		},
  },
	//订单信息
	{
		name:'Order',
		path:'/order',
		component:()=>import('@/views/Order.vue'),
		meta:{
				title:'订单信息',
				icon:'',
				roles:['admin','buyer','manager','seller'],
				root:'OrderRoot',
				index:0
			},
	},
	//订单详情
	{
		name:'OrderDetail',
		path:'/orderDetail',
		component:()=>import('@/views/OrderDetail.vue'),
		meta:{
				title:'订单详情',
				icon:'',
				roles:['admin','buyer','manager','seller'],
				root:'',
				index:0
			},
	},
	//退单信息
	{
		name:'Return',
		path:'/return',
		component:()=>import('@/views/Order.vue'),
		meta:{
				title:'退单信息',
				icon:'',
				roles:['admin','buyer','manager','seller'],
				root:'ReturnRoot',
				index:0
			},
	},
	//退单详情
	{
		name:'ReturnDetail',
		path:'/returnDetail',
		component:()=>import('@/views/OrderDetail.vue'),
		meta:{
				title:'退单详情',
				icon:'',
				roles:['admin','buyer','manager','seller'],
				root:'',
				index:0
			},
	},
	//货物查询
	{
		name:'GoodsSelect',
		path:'/goodsSelect',
		component:()=>import('@/views/Goods.vue'),
		meta:{
				title:'货物查询',
				icon:'',
				roles:allRoles,
				root:'StoreRoot',
				index:0
			},
	},
	//出入审批
	{
		name:'InOutCheck',
		path:'/inOutCheck',
		component:()=>import('@/views/StoreApply.vue'),
		meta:{
				title:'存取审批',
				icon:'',
				roles:['admin','storeman'],
				root:'StoreRoot',
				index:1
			},
	},
	//库存日志
	// {
	// 	name:'GoodsLog',
	// 	path:'/goodsLog',
	// 	component:()=>import('@/views/Home.vue'),
	// 	meta:{
	// 			title:'库存日志',
	// 			icon:'',
	// 			roles:['admin','storeman'],
	// 			root:'StoreRoot',
	// 			index:2
	// 		},
	// },
  //交易额分析
  {
  	name:'PriceAnalysis',
  	path:'/priceAnalysis',
  	component:()=>import('@/views/PriceAnalysis.vue'),
  	meta:{
  			title:'交易额分析',
  			icon:'',
  			roles:allRoles,
  			root:'AnalysisRoot',
  			index:0
  		},
  },
  //交易量分析
  {
  	name:'CountAnalysis',
  	path:'/countAnalysis',
  	component:()=>import('@/views/CountAnalysis.vue'),
  	meta:{
  			title:'交易量分析',
  			icon:'',
  			roles:allRoles,
  			root:'AnalysisRoot',
  			index:1
  		},
  },
  //默认页
  {
  	name:'DefaultChild',
  	path:'*',
  	component:()=>import('@/views/Home.vue'),
  	meta:{
  			title:'默认页',
  			icon:'',
  			roles:allRoles,
  			root:'',
  			index:0
  		},
  },
];
export {allRoles,allRolesObj};
export default menuRouter;
