const typeText={
	clientType:['供应商','客户'],
	goodsType:['物料','产品'],
	goodsState:['正常','低库存','高库存'],
	goodsStateColor:['green','blue','red'],
	needPlanType:['需求','计划'],
	buySellType:['采购','生产','销售'],
	level:['一般','急','紧急'],
	levelColor:['green','orange','red'],
	needPlanState:['待确认','进行中','已完成','未通过'],
	needPlanStateColor:['orange','blue','green','red'],
	npDetailState:['待确认','进行中','已完成','未通过'],
	npDetailStateColor:['orange','blue','green','red'],
	orderType:['采购订单','销售订单','采购退单','销售退单'],
	orderState:['待审核','进行中','已完成','未通过'],
	orderStateColor:['orange','blue','green','red'],
	orderDetailState:['未完成','已完成'],
	orderDetailStateColor:['orange','green'],
	inOutType:['入库','出库'],
	storeApplyState:['待确认','进行中','已完成','未通过'],
	storeApplyStateColor:['orange','blue','green','red'],
  fileMaxSize:{
    value:2048,
    unit:'KB',
  },
  fileTypeArr:['.jpg','.jpeg','.png'],
};
export {typeText};
